name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install -y libegl1-mesa-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with black
      run: |
        black --check .
    - name: Type check with mypy
      run: |
        mypy pyside6_qml_stubgen.py tests --exclude tests/target
    - name: Test with pytest
      run: |
        pytest
    - name: Build wheel
      if: matrix.os == 'ubuntu-latest'
      run: |
        python -m build
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: pyside6-qml-stubgen-wheel
        path: dist/*

  upload-pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/pyside6-qml-stubgen
    permissions:
      id-token: write
    concurrency:
      group: "deploy-pypi"
      cancel-in-progress: false
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: pyside6-qml-stubgen-wheel
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
